name: Auto Deployment

on:
  push:
    branches: [ main, woog2roid-ghactions_autodeploy ]

env:
  REACT_APP_SERVER_API: ${{secrets.REACT_APP_SERVER_API}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - run : npm i
      shell: bash
    - run : npm ci
      shell: bash
    - run : git config user.name github-actions
      shell: bash
    - run : git config user.email github-actions@github.com
      shell: bash
    - run :  CI=false npm run deploy
      shell: bash
